### ISSUE TITLE
registration_errors function working

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITKTutorialSPIE2017#4]
Hi,

This is not an issue, this is regarding a problem I have been encountered in image registration.
Let me first discuss my problem in brief.
## Experiment : 
1. I have a reference image and a moving image.(multimodal image)
2. Registered using lets say method A, B , C, and D.
3. I just want to compare A,B,C,D's accuracy in registration.
4. I don't have any golden point-set database, neither it is possible in my case. I have only three image, fixed, moving and registered.
## Thoughts :
Now while I come across this registration_utilities function, I thought if the fixed image is registered with moving image accurately, then ideal case, fixed image coordinate space = registered image coordinate space.
Now if we pass some random point from Fixed image in two arguments of registration_errors(fixed_image_random,fixed_image_random,transformation_matrix).
Then fixed_image_random will be transformed to a new point set, and will be compared with fixed_image_random in some sort of distance measurements. Should this be a measure for accuracy of registration?

## Other Inputs:
Is there any other way to check which method A,B,C,D is better in registration. How can we measure registration accuracy with just
1. Fixed image
2. Moving Image
3. TransformationA, TransformationB, TransformationC, TransformationD
Thanks

**Comment by blowekamp** [comment]
I think this issue is meant for the InsightSoftwareConsortium/SimpleITK-Notebooks/issues repository.
