### ISSUE TITLE
myshow3D.py for a 3D image

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITKTutorialSPIE2017#5]
Hi,

If I want to show a 3D image let say (512*512)*60 slices. The function is failed to give any output rendering the 3D image. I think there is some conceptual issue. Will it be able to show any kind of 3D image, like [http://docs.enthought.com/mayavi/mayavi/](url) is for brain(not accurate though). Is there any other way to visualize a stack of images in 3D space?

Thanks

**Comment by blowekamp** [comment]
I think this issue is meant for the InsightSoftwareConsortium/SimpleITK-Notebooks/issues repository.
