### ISSUE TITLE
generate_random_pointset functional behavior

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITKTutorialSPIE2017#6]
Hi,
To generate some random points inside the image only, we must ensure that we are taking points which have intensity value > 0. The input is a SimpleITK.Image. the domain or size does not ensure that the image has only nonzero pixel. Suppose we have a 512*512 image but the Field of view of the image is in 120*80 or may be it can not be depicted in rectangular tile. It may have a shape or different anatomy. So my question is we should check whether the pixel value is > 0 at that point.Right? Otherwise we may somehow skip relevant point. Though the whole 512*512 get registered. Still we will be interested on random points which are actually inside the image, I guess. How should we proceed in that case? 

Is there any bound of how many random points should we take for best results in suppose for 512*512? It is clear that we should not take a huge number of points from the set, it will nullify the registration error in some sense. (mean / SD). Please suggest.

Thanks

**Comment by blowekamp** [comment]
I think this issue is meant for the InsightSoftwareConsortium/SimpleITK-Notebooks/issues repository.
